name: Validate Commits

on:
  push:
  pull_request:

jobs:
  prevent-fixup-commits:
    name: prevent-fixup-commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ianwremmel/prevent-fixup-commits@f52dc067662b1d71b4cfbb13e2ca2d1ea71bf612 # v1.0.8

  prevent-nopush-commits:
    name: prevent-nopush-commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ianwremmel/prevent-nopush-commits@8bf416b9675b3b781dd7426b549f2f03f9744d46 # v1.0.8
